### PR TITLE
Make init-letsencrypt.sh executable so that users don't have to

### PR DESCRIPTION
**Pull request by aspiers**
git tracks file permissions, so we don't need to rely on users doing this.

### CODE REVIEW

**Comment by wmnnd** [comment]
@aspiers Thank you for the suggestion.
As @wagnerdelima points out, this PR doesn’t actually make the file executable, so I’ve pushed my own commit for this :smile:

**Comment by aspiers** [comment]
This PR *does* make the file executable.  I'm not sure how you both missed it :laughing:  Look where the mouse pointer is pointing in this image:

image

If you look at your own pull request #25 you'll see exactly the same thing.  But by not merging mine you are now missing the corresponding updates to the README.md.  So please can you reopen and merge mine?

**Comment by wmnnd** [comment]
Oh, sorry, you’re right!
Could you adjust the README modification to use triple backtick instead of indentation for the code blocks?

**Comment by aspiers** [comment]
>Could you adjust the README modification to use triple backtick instead of indentation for the code blocks?

I could, but are you sure you want that?  Quoting directly from https://daringfireball.net/projects/markdown/:

>The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible. The idea is that a Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions.

IMHO the indented version is significantly more in line with these goals than the backticks version.

**Pull request merged**
