### PR TITLE
Add looping over the domains

### PR DESCRIPTION
**Pull request by sihorton**
Simple change to the init script. It now reads from a domains.txt file and for each line in the file it will create the dummy certificates, then it starts up nginx, and then loops over the domains.txt file once again and requests a new certificate.

Tested for a server I have that needed to have multiple domains so hopefully it works in general. 

The idea was taken from the code in Issue #6 but instead of taking from parameters it reads from the domains.txt file.

### CODE REVIEW

**Comment by marcelomaia** [comment]
very nice!

**Comment by fluse** [comment]
this is really nice!

**Comment by wmnnd** [comment]
Hey @sihorton, thank you for your suggestion!

I’don’t think this is a very good idea, as it is.
Your implementation would create keys and certificates for each domain; and that is undesirable – especially when you have a larger number of domains, since you’ll hit the rate limits of Let’s Encrypt like that.

My preferred solution would be to modify the current script and allow a parameter for specifying domains, like this:
`./init-letsencrypt.sh -d example.com -d example.org`

This could be combined with an additional `--domains-file` parameter.
`./init-letsencrypt.sh --domains-file domains.txt`

What do you think?

**Comment by sihorton** [comment]
Sure go with what you think is best. It is great if you can extend the current script to support multiple domains however you feel works best.

**Comment by vesamet** [comment]
Out of curiosity, when will this be merged ?

**Comment by vesamet** [comment]
I hope this will be updated eventually :P !

**Comment by wmnnd** [comment]
Hey folks, I’ve added the `--domain` argument to the new [2.x branch](https://github.com/wmnnd/nginx-certbot/tree/2.x) which should make this a lot easier!
@sihorton Would you want to adjust your merge request to work with the updated v2 script and add the `--domains-file` argument?

As an alternative for now, I’ve found this suggestion in the Let’s Encrypt forum which will now also work with `init-letsencrypt.sh`:
`$(sed 's/^/-d /' domains.txt)`

**Pull request closed without merging**
