### PR TITLE
feat: remove `docker-compose` as a dependency

### PR DESCRIPTION
**Pull request by okeyokoro**
I had trouble deploying this setup on a GCP VM
running their "Container-Optimized OS"

See reasons here:
https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os

Refactoring this script allowed me to get up & running.

I think if you accepted these changes,
You would make the software more accessible

### CODE REVIEW

**Comment by wmnnd** [comment]
Hey @okeyokoro, thank you for your merge request!
I wonder if this might have any weird side-effects on machines that do have docker-compose, though …

**Comment by okeyokoro** [comment]
@wmnnd thank _**you**_, for making this awesome repo!

>  any weird side-effects on machines that do have docker-compose,

^ this is a totally valid point, that I didn't pay much consideration tbh

in theory, we should be good (since it's just a container). but I can't say i'm 100% certain that there won't be any surprises

---

If you'd like;

a `read` could be added; prompting the user to choose either one of the methods

^ after the prompt we would simply define `dc` to either use:

- `docker-compose "$@"` or
- `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.24.0 "$@"`

**Comment by wmnnd** [comment]
Do you think you could modify this for the 2.x branch so that it uses docker-compose when installed and otherwise asks the user whether they want to continue using compose in a container? Maybe allow skipping the question with a parameter like `--docker-compose-in-docker`.

**Comment by okeyokoro** [comment]
sounds great, I'll get to work on that 🙂

**Comment by okeyokoro** [comment]
closing this since i've got #57 up

**Pull request closed without merging**
